language: cpp
os:
  - linux
  - osx

compiler: gcc
sudo: required
before_install:
  - ./scripts/travis_setup.sh

after_install:
  - g++ --version

script:
  - cmake -H. -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=g++-4.8 -DCMAKE_INSTALL_PREFIX=dist_omp -DSURFACE_BUILD_WITH_OPENMP=On -DBUILD_SHARED_LIBS=On -DCMAKE_BUILD_TYPE=Release -Bbuild_omp
  - make -C build_omp VERBOSE=1
  - cmake -H. -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=g++-4.8 -DCMAKE_INSTALL_PREFIX=dist -DSURFACE_BUILD_WITH_OPENMP=Off -DBUILD_SHARED_LIBS=On -DCMAKE_BUILD_TYPE=Release -Bbuild
  - make -C build VERBOSE=1

notifications:
  slack: rikenhivedev:s4uUK1Vrn0rCh4OXTXUf5Tw
